backend:
  name: git-gateway
  branch: main
local_backend: true
media_folder: /public/assets
public_folder: /assets
collections:
  - name: posts
    label: Posts
    create: true
    folder: posts
    fields:
      - name: title
        label: Title
      - name: body
        title: Body
        widget: markdown
